[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint.per-file-ignores]
"server.py" = ["N802"]

# Include useful rule sets
[tool.ruff.lint]
extend-select = [
  "E",   # pycodestyle (includes trailing newline W292)
  "F",   # pyflakes
  "B",   # flake8-bugbear
  "N",   # pep8-naming
  "UP",  # pyupgrade
  "C90", # mccabe complexity
  "I",   # isort (import sorting)
  "W",   # additional warnings like W292
]

[tool.coverage.run]
omit = [
  "*/test/*"
]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
