@startuml
!include /home/mflkee/.config/plantuml/dracula.puml
start

:Игрок вводит слово;

:Проверка длины слова;
if (Длина слова не равна 5?) then (yes)
  :Выдать исключение "Слово должно состоять из 5 символов";
  stop
else (no)
  :Преобразовать слово в верхний регистр;
  :Увеличить количество попыток;

  :Инициализация пустого списка подсказок (response = [0, 0, 0, 0, 0]);

  :Для каждой буквы в слове (индекс i от 0 до 4) выполнить:
  - если буква на текущей позиции совпадает с буквой в слове:
    - установить значение 2 в response[i]
  :Для каждой буквы в слове (индекс i от 0 до 4):
  - если буква на текущей позиции не совпала с буквой в слове, но присутствует в слове:
    - установить значение 1 в response[i];

  :Вернуть список подсказок (response);

end
@enduml
